version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1989
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  app:
    build: .
    command: python manage.py migrate && python runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    depends_on:
      - db

volumes:
  pg_data: