version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    healthcheck:
      test: pg_isready -U ${USER} -d ${NAME}
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: